executable = /bin/bash
arguments = /lustre/home/dschmotz/skill-inject/apptainer/debug_build.sh
output = /lustre/home/dschmotz/skill-inject/apptainer/debug_$(Cluster).out
error  = /lustre/home/dschmotz/skill-inject/apptainer/debug_$(Cluster).err
log    = /lustre/home/dschmotz/skill-inject/apptainer/debug_$(Cluster).log
request_cpus   = 2
request_memory = 4096
request_disk   = 10G
+BypassLXCfs = "true"
queue
