executable = /bin/bash
arguments = /lustre/home/dschmotz/skill-inject/apptainer/run_smoke_task.sh
output = /lustre/home/dschmotz/skill-inject/apptainer/run_smoke_task_$(Cluster).out
error  = /lustre/home/dschmotz/skill-inject/apptainer/run_smoke_task_$(Cluster).err
log    = /lustre/home/dschmotz/skill-inject/apptainer/run_smoke_task_$(Cluster).log

request_cpus   = 2
request_memory = 4096
request_disk   = 5G

+BypassLXCfs = "true"

queue
